TEXTBLOCK ToolBar C:\CAVO27\Programme\SEUIXP\Explorer16.bmp
//Prefix = IDTB_
//Width  = 16
//Color  = 16711935
DEFINE IDTB_Back := 1l
DEFINE IDTB_Forward := 2l
DEFINE IDTB_New := 3l
DEFINE IDTB_Cut := 4l
DEFINE IDTB_Copy := 5l
DEFINE IDTB_Paste := 6l
DEFINE IDTB_Delete := 7l
DEFINE IDTB_Undo := 8l
DEFINE IDTB_Redo := 9l
DEFINE IDTB_CopyTo := 10l
DEFINE IDTB_Favorites := 11l
DEFINE IDTB_Options := 12l
DEFINE IDTB_Folders := 13l
DEFINE IDTB_History := 14l
DEFINE IDTB_Home := 15l
DEFINE IDTB_Mail := 16l
DEFINE IDTB_MoveTo := 17l
DEFINE IDTB_Open := 18l
DEFINE IDTB_Save := 19l
DEFINE IDTB_Print := 20l
DEFINE IDTB_Preview := 21l
DEFINE IDTB_Properties := 22l
DEFINE IDTB_Refresh := 23l
DEFINE IDTB_Search := 24l
DEFINE IDTB_Stop := 25l
DEFINE IDTB_Up := 26l
DEFINE IDTB_Views := 27l
